version: '3.1'

services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "3000:80"
        environment:
            API_ADDRESS: 10.0.0.10:8080